Repository rohitagr0310/Bookflow-app, pull requests merged in 2023-10, with the labels that each got.

#227 login and signup for hosted website
  functions/login.js
  functions/signup.js
  package.json
  yarn.lock
Labels: enhancement, backend, deployment, Hacktoberfest-accepted

#230 add huskey as well as templates for issue opening
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation_work.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  package.json
  yarn.lock
Labels: documentation, Hacktoberfest-accepted

#232 Issue no #226 fixed
  src/pages/home_page/_HomePage.css
  yarn.lock
Labels: enhancement, Hacktoberfest-accepted

#243 code of conduct updated successfully
  .github/workflows/Checks.yml
  .github/workflows/eslint.yml
  CODE_OF_CONDUCT.md
Labels: documentation, Hacktoberfest-accepted

#245 Lazy loading added with loader
  package.json
  src/App.js
  src/components/Loader.js
  src/pages/admin_panel/AdminPanel.jsx
  yarn.lock
Labels: enhancement, Hacktoberfest-accepted

#251 Feature/bg fix
  .gitignore
  src/pages/home_page/_HomePage.css
Labels: enhancement, Hacktoberfest-accepted

#255 Made changes in the footer
  src/components/footer/Footer.jsx
  src/components/footer/_Footer.css
  src/pages/login_page/term_condition/TermsAndConditions.css
  src/pages/login_page/term_condition/TermsAndConditions.jsx
Labels: enhancement, Hacktoberfest-accepted

#258 Make Contact Us Page
  src/pages/contact-us/ContactUs.css
  src/pages/contact-us/ContactUs.jsx
Labels: enhancement, Hacktoberfest-accepted

#263 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, enhancement, Hacktoberfest-accepted

#264 Develop
  .github/workflows/Checks.yml
  .github/workflows/eslint.yml
  .gitignore
  CODE_OF_CONDUCT.md
  package.json
  src/App.js
  src/components/Loader.js
  src/components/footer/Footer.jsx
  src/components/footer/_Footer.css
  src/pages/admin_panel/AdminPanel.jsx
  src/pages/home_page/HomePage.jsx
  src/pages/home_page/_HomePage.css
  src/pages/login_page/term_condition/TermsAndConditions.css
  src/pages/login_page/term_condition/TermsAndConditions.jsx
  yarn.lock
Labels: Hacktoberfest-accepted

#272 BarCode
  B.jpg
  BarCode.jsx
  CONTRIBUTING.md
  src/pages/contact-us/ContactUs.css
  src/pages/contact-us/ContactUs.jsx
  src/pages/login_page/_ForgetPassword.css
Labels: enhancement, Hacktoberfest-accepted

#273 update styling in testimonial
  src/pages/home_page/_HomePage.css
Labels: enhancement, Hacktoberfest-accepted

#276 Width of content
  src/pages/home_page/HomePage.jsx
  src/pages/home_page/_HomePage.css
Labels: enhancement, Hacktoberfest-accepted

#288 About Us Update
  B.jpg
  BarCode.jsx
  CONTRIBUTING.md
  src/components/barcode/BarCode.jsx
  src/components/footer/Footer.jsx
  src/pages/about_us/AboutUs.jsx
  src/pages/contact-us/ContactUs.css
  src/pages/contact-us/ContactUs.jsx
  src/pages/home_page/HomePage.jsx
  src/pages/home_page/_HomePage.css
  src/pages/login_page/_ForgetPassword.css
Labels: enhancement, Hacktoberfest-accepted

#290 Update README.md
  README.md
Labels: documentation, Hacktoberfest-accepted

#291 Student UI improve
  src/pages/student_panel/StudentPanel.css
  src/pages/student_panel/StudentPanel.jsx
  src/pages/student_panel/student_pages/StudentIssued.css
  src/pages/student_panel/student_pages/StudentIssued.jsx
Labels: enhancement, Hacktoberfest-accepted

#294 Add files via upload
  Bookflow.png
Labels: update, Hacktoberfest-accepted

#295 updating the code
  README.md
  package.json
  src/pages/about_us/AboutUs.jsx
  yarn.lock
Labels: Hacktoberfest-accepted

#296 updating develop branch
  README.md
  package.json
  src/App.js
  src/pages/about_us/AboutUs.jsx
  yarn.lock
Labels: Hacktoberfest-accepted

#297 Home UI redesign
  public/index.html
  src/App.js
  src/components/footer/Footer.jsx
  src/components/footer/_Footer.css
  src/images/vector1.png
  src/images/vector2.png
  src/images/vector5.png
  src/index.css
  src/pages/home_page/HomePage.jsx
  src/pages/home_page/_HomePage.css
  src/pages/home_page/header/Header.jsx
  src/pages/home_page/header/_Header.css
Labels: enhancement, Hacktoberfest-accepted

#298 Develop
  public/index.html
  src/App.js
  src/components/footer/Footer.jsx
  src/components/footer/_Footer.css
  src/images/vector1.png
  src/images/vector2.png
  src/images/vector5.png
  src/index.css
  src/pages/home_page/HomePage.jsx
  src/pages/home_page/_HomePage.css
  src/pages/home_page/header/Header.jsx
  src/pages/home_page/header/_Header.css
Labels: enhancement, deployment, Hacktoberfest-accepted

#301 Update contactus page
  src/pages/contact-us/ContactUs.css
Labels: enhancement, Hacktoberfest-accepted

#309 Update README.md
  README.md
Labels: documentation, Hacktoberfest-accepted

#313 Fixed the horizontal bar / horizontal overflow issue
  src/index.css
Labels: enhancement, Hacktoberfest-accepted

#311 contact us page responsive
  src/pages/contact-us/ContactUs.css
Labels: enhancement, Hacktoberfest-accepted

#315 newHeader
  src/App.js
  src/components/header/Header.jsx
  src/components/header/_Header.css
  src/pages/about_us/AboutUs.jsx
  src/pages/home_page/HomePage.jsx
Labels: enhancement, Hacktoberfest-accepted

#324 Update README.md: Added Contributors Image Icon
  README.md
Labels: enhancement, Hacktoberfest-accepted

#323 Bottom spacing
  public/index.html
  src/pages/contact-us/ContactUs.css
Labels: enhancement, Hacktoberfest-accepted

#325 Add hover effect to know more button in landing page. issue #316
  src/pages/home_page/_HomePage.css
Labels: enhancement, Hacktoberfest-accepted

#329 Solved all Mentioned bugs
  pnpm-lock.yaml
  src/App.js
  src/components/header/Header.jsx
  src/components/header/_Header.css
  src/pages/home_page/HomePage.jsx
  src/pages/home_page/_HomePage.css
  src/pages/login_page/AuthPage.jsx
  src/pages/login_page/_AuthPage.css
  src/pages/login_page/term_condition/TermsAndConditions.css
Labels: Hacktoberfest-accepted, bug-fix

#334 Made the Navbar Responsive to Mobile Screens With a Hambuger Menu
  src/components/header/Header.jsx
  src/components/header/_Header.css
Labels: Hacktoberfest-accepted, bug-fix

#335 feature/Update TwitterIcon (fixes #330)
  package.json
  src/components/footer/Footer.jsx
  yarn.lock
Labels: enhancement, Hacktoberfest-accepted

#337 updating qa branch in my local machine
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/documentation.yaml
  .github/ISSUE_TEMPLATE/documentation_work.md
  .github/ISSUE_TEMPLATE/feature.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/proposal.yaml
  .github/ISSUE_TEMPLATE/question.md
  .github/workflows/greetings.yml
  .github/workflows/label.yml
  .github/workflows/stale.yml
  CONTRIBUTORS.md
  README.md
  package.json
  pnpm-lock.yaml
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App.js
  src/components/footer/Footer.jsx
  src/components/footer/_Footer.css
  src/components/header/Header.jsx
  src/components/header/_Header.css
  src/images/vector1.png
  src/images/vector2.png
  src/images/vector5.png
  src/index.css
  src/pages/about_us/AboutUs.jsx
  src/pages/contact-us/ContactUs.css
  src/pages/home_page/HomePage.jsx
  src/pages/home_page/_HomePage.css
  src/pages/home_page/header/Header.jsx
  src/pages/home_page/header/_Header.css
  src/pages/login_page/AuthPage.jsx
  src/pages/login_page/_AuthPage.css
  src/pages/login_page/term_condition/TermsAndConditions.css
  yarn.lock
Labels: update, Hacktoberfest-accepted

#339 Improved UI for Student Panel to resolve #303
  src/pages/student_panel/StudentPanel.jsx
  src/pages/student_panel/StudentlistItems.jsx
  src/pages/student_panel/_student-panel-styles.css
  src/pages/student_panel/student_pages/StudentAccount.jsx
  src/pages/student_panel/student_pages/StudentHistory.jsx
  src/pages/student_panel/student_pages/StudentIssued.jsx
  src/pages/student_panel/student_pages/StudentRequests.jsx
  src/pages/student_panel/student_pages/StudentSearch.jsx
Labels: enhancement, Hacktoberfest-accepted

#341 Label Fix
  src/pages/home_page/_HomePage.css
  src/pages/login_page/AuthPage.jsx
  src/pages/login_page/_AuthPage.css
Labels: enhancement, Hacktoberfest-accepted

#340 UI Enhancement
  src/pages/home_page/_HomePage.css
Labels: enhancement, Hacktoberfest-accepted

#342 Revert 341 feature/login form label fix
  src/pages/student_panel/StudentPanel.jsx
  src/pages/student_panel/StudentlistItems.jsx
  src/pages/student_panel/_student-panel-styles.css
  src/pages/student_panel/student_pages/StudentAccount.jsx
  src/pages/student_panel/student_pages/StudentHistory.jsx
  src/pages/student_panel/student_pages/StudentIssued.jsx
  src/pages/student_panel/student_pages/StudentRequests.jsx
  src/pages/student_panel/student_pages/StudentSearch.jsx
Labels: Hacktoberfest-accepted

#343 Improve in UI for Admin panel
  src/pages/admin_panel/AdminPanel.jsx
  src/pages/admin_panel/Deposits.jsx
  src/pages/admin_panel/admin_pages/AddBook.jsx
  src/pages/admin_panel/admin_pages/AdminHistory.jsx
  src/pages/admin_panel/admin_pages/AllBooks.jsx
  src/pages/admin_panel/admin_pages/IssuedBooks.jsx
  src/pages/admin_panel/admin_pages/ManageStudents.jsx
  src/pages/admin_panel/admin_pages/PendingIssue.jsx
  src/pages/admin_panel/pending.jsx
Labels: enhancement, Hacktoberfest-accepted

#345 added-FAQ-page
  package.json
  src/App.js
  src/pages/faqs/faqs.css
  src/pages/faqs/faqs.jsx
  src/pages/home_page/HomePage.jsx
Labels: enhancement, Hacktoberfest-accepted
