Repository rohitagr0310/Bookflow-app, pull requests merged in 2023-09, with the labels that each got.

#101 Qa
  backend/controllers/adminController.js
  backend/routes/adminRoutes.js
  src/components/qrcodescanner/QRCodeScanner.jsx
  src/components/timedpopup/TimedPopup.jsx
  src/pages/admin_panel/AdminHeader.jsx
  src/pages/admin_panel/AdminNav.jsx
  src/pages/admin_panel/AdminPanel.jsx
  src/pages/admin_panel/_admin-nav.css
  src/pages/admin_panel/_admin-panel-styles.css
  src/pages/admin_panel/admin_pages/AllBooks.jsx
  src/pages/admin_panel/admin_pages/_add-book.css
  src/pages/admin_panel/admin_pages/_admin-account.css
  src/pages/login_page/AuthPage.jsx
  src/pages/login_page/_AuthPage.css
  src/pages/student_panel/_StudentNav.css
  src/pages/student_panel/student_pages/_studentAccount.css
Labels: update

#103 Update main
  .eslintrc.js
  backend/controllers/adminController.js
  backend/controllers/authController.js
  backend/db.js
  backend/index.js
  backend/package.json
  backend/routes/adminRoutes.js
  backend/routes/authRoutes.js
  backend/yarn.lock
  package.json
  src/App.js
  src/components/footer/Footer.jsx
  src/components/footer/_Footer.css
  src/components/qrcodescanner/QRCodeScanner.jsx
  src/components/timedpopup/TimedPopup.jsx
  src/pages/admin_panel/AdminHeader.jsx
  src/pages/admin_panel/AdminNav.jsx
  src/pages/admin_panel/AdminPanel.jsx
  src/pages/admin_panel/_admin-nav.css
  src/pages/admin_panel/_admin-panel-styles.css
  src/pages/admin_panel/admin_pages/AllBooks.jsx
  src/pages/admin_panel/admin_pages/_add-book.css
  src/pages/admin_panel/admin_pages/_admin-account.css
  src/pages/home_page/HomePage.jsx
  src/pages/home_page/_HomePage.css
  src/pages/login_page/AuthPage.jsx
  src/pages/login_page/_AuthPage.css
  src/pages/student_panel/StudentHeader.jsx
  src/pages/student_panel/StudentNav.jsx
  src/pages/student_panel/StudentPanel.jsx
  src/pages/student_panel/_StudentHeader.css
  src/pages/student_panel/_StudentNav.css
  src/pages/student_panel/student_pages/BookIssued.jsx
  src/pages/student_panel/student_pages/BooksIssued.jsx
  src/pages/student_panel/student_pages/Feedback.jsx
  src/pages/student_panel/student_pages/StudentHomepage.jsx
  src/pages/student_panel/student_pages/_feedback.css
  src/pages/student_panel/student_pages/_issuedbook.css
  src/pages/student_panel/student_pages/_studentAccount.css
  src/pages/student_panel/student_pages/_studenthomepage.css
  tempCodeRunnerFile.javascript
Labels: update

#100 add book function compleeted
  .eslintrc.js
  backend/controllers/adminController.js
  backend/controllers/bookController.js
  backend/routes/adminRoutes.js
  backend/routes/bookRoutes.js
  src/App.js
  src/pages/admin_panel/AdminHeader.jsx
  src/pages/admin_panel/admin_pages/AddBook.jsx
  src/pages/admin_panel/admin_pages/AdminAccount.jsx
Labels: duplicate, enhancement, good first issue, backend

#106 some padding removed
  src/pages/admin_panel/AdminHeader.jsx
  src/pages/admin_panel/_admin-panel-styles.css
  src/pages/home_page/HomePage.jsx
  src/pages/home_page/_HomePage.css
  src/pages/student_panel/StudentHeader.jsx
  src/pages/student_panel/_StudentHeader.css
Labels: bug, enhancement

#109 homepage sections fixed
  src/images/background.jpg
  src/images/background2.jpg
  src/images/background3.jpg
  src/images/background4.jpg
  src/images/loginPage-bg.jpeg
  src/pages/home_page/HomePage.jsx
  src/pages/home_page/_HomePage.css
Labels: bug, enhancement, question

#111 Contact Us Page
  .eslintrc.js
  backend/controllers/adminController.js
  backend/controllers/bookController.js
  backend/routes/adminRoutes.js
  backend/routes/bookRoutes.js
  src/App.js
  src/components/footer/Footer.jsx
  src/components/qrcodescanner/QRCodeScanner.jsx
  src/components/timedpopup/TimedPopup.jsx
  src/images/background.jpg
  src/images/background2.jpg
  src/images/background3.jpg
  src/images/background4.jpg
  src/images/loginPage-bg.jpeg
  src/pages/admin_panel/AdminHeader.jsx
  src/pages/admin_panel/AdminNav.jsx
  src/pages/admin_panel/AdminPanel.jsx
  src/pages/admin_panel/_admin-nav.css
  src/pages/admin_panel/_admin-panel-styles.css
  src/pages/admin_panel/admin_pages/AddBook.jsx
  src/pages/admin_panel/admin_pages/AdminAccount.jsx
  src/pages/admin_panel/admin_pages/AllBooks.jsx
  src/pages/admin_panel/admin_pages/_add-book.css
  src/pages/admin_panel/admin_pages/_admin-account.css
  src/pages/home_page/ContactUs.jsx
  src/pages/home_page/HomePage.jsx
  src/pages/home_page/_ContactUs.css
  src/pages/home_page/_HomePage.css
  src/pages/login_page/AuthPage.jsx
  src/pages/login_page/ForgetPass.jsx
  src/pages/login_page/_AuthPage.css
  src/pages/student_panel/StudentHeader.jsx
  src/pages/student_panel/StudentNav.jsx
  src/pages/student_panel/_StudentHeader.css
  src/pages/student_panel/_StudentNav.css
  src/pages/student_panel/student_pages/_studentAccount.css
Labels: duplicate, enhancement, good first issue, help wanted

#114 Devlop
  .eslintrc.js
  backend/controllers/adminController.js
  backend/controllers/bookController.js
  backend/routes/adminRoutes.js
  backend/routes/bookRoutes.js
  backend/routes/statusRoute.js
  src/App.js
  src/components/footer/Footer.jsx
  src/components/qrcodescanner/QRCodeScanner.jsx
  src/components/timedpopup/TimedPopup.jsx
  src/images/background.jpg
  src/images/background2.jpg
  src/images/background3.jpg
  src/images/background4.jpg
  src/images/loginPage-bg.jpeg
  src/pages/admin_panel/AdminHeader.jsx
  src/pages/admin_panel/AdminNav.jsx
  src/pages/admin_panel/AdminPanel.jsx
  src/pages/admin_panel/Deposits.jsx
  src/pages/admin_panel/Orders.jsx
  src/pages/admin_panel/_admin-nav.css
  src/pages/admin_panel/_admin-panel-styles.css
  src/pages/admin_panel/admin_pages/AddBook.jsx
  src/pages/admin_panel/admin_pages/AdminAccount.jsx
  src/pages/admin_panel/admin_pages/AllBooks.jsx
  src/pages/admin_panel/admin_pages/_add-book.css
  src/pages/admin_panel/admin_pages/_admin-account.css
  src/pages/admin_panel/listItems.jsx
  src/pages/home_page/ContactUs.jsx
  src/pages/home_page/HomePage.jsx
  src/pages/home_page/_ContactUs.css
  src/pages/home_page/_HomePage.css
  src/pages/login_page/AuthPage.jsx
  src/pages/login_page/ForgetPass.jsx
  src/pages/login_page/_AuthPage.css
  src/pages/student_panel/StudentHeader.jsx
  src/pages/student_panel/StudentNav.jsx
  src/pages/student_panel/_StudentHeader.css
  src/pages/student_panel/_StudentNav.css
  src/pages/student_panel/student_pages/_studentAccount.css
Labels: update

#115 Devlop
  backend/index.js
  src/pages/admin_panel/AdminHeader.jsx
  src/pages/admin_panel/AdminPanel.jsx
  src/pages/admin_panel/Deposits.jsx
  src/pages/admin_panel/_admin-nav.css
  src/pages/admin_panel/listItems.jsx
  src/pages/admin_panel/pending.jsx
Labels: update

#116 Homepage done
  .eslintrc.js
  backend/controllers/adminController.js
  backend/controllers/bookController.js
  backend/routes/adminRoutes.js
  backend/routes/bookRoutes.js
  src/App.js
  src/components/footer/Footer.jsx
  src/components/qrcodescanner/QRCodeScanner.jsx
  src/components/timedpopup/TimedPopup.jsx
  src/images/b.jpg
  src/images/background.jpg
  src/images/background1.jpg
  src/images/background2.jpg
  src/images/background3.jpg
  src/images/background4.jpg
  src/images/loginPage-bg.jpeg
  src/images/new1.jpg
  src/images/new2.png
  src/images/new3.png
  src/images/new4.png
  src/images/new5.png
  src/images/potrait lib.jpg
  src/images/quote.png
  src/images/vector1.png
  src/images/vector2.png
  src/images/vector3.png
  src/images/vector4.png
  src/images/vector5.png
  src/images/vector6.png
  src/pages/admin_panel/AdminHeader.jsx
  src/pages/admin_panel/AdminNav.jsx
  src/pages/admin_panel/AdminPanel.jsx
  src/pages/admin_panel/_admin-nav.css
  src/pages/admin_panel/_admin-panel-styles.css
  src/pages/admin_panel/admin_pages/AddBook.jsx
  src/pages/admin_panel/admin_pages/AdminAccount.jsx
  src/pages/admin_panel/admin_pages/AllBooks.jsx
  src/pages/admin_panel/admin_pages/_add-book.css
  src/pages/admin_panel/admin_pages/_admin-account.css
  src/pages/home_page/ContactUs.jsx
  src/pages/home_page/HomePage.jsx
  src/pages/home_page/_ContactUs.css
  src/pages/home_page/_HomePage.css
  src/pages/home_page/header/Header.jsx
  src/pages/home_page/header/_Header.css
  src/pages/login_page/AuthPage.jsx
  src/pages/login_page/ForgetPass.jsx
  src/pages/login_page/_AuthPage.css
  src/pages/student_panel/StudentHeader.jsx
  src/pages/student_panel/StudentNav.jsx
  src/pages/student_panel/_StudentHeader.css
  src/pages/student_panel/_StudentNav.css
  src/pages/student_panel/student_pages/_studentAccount.css
  yarn.lock
Labels: enhancement

#117 Forget password functionality
  backend/index.js
  backend/routes/statusRoute.js
  src/App.js
  src/pages/admin_panel/AdminHeader.jsx
  src/pages/admin_panel/AdminPanel.jsx
  src/pages/admin_panel/Deposits.jsx
  src/pages/admin_panel/_admin-nav.css
  src/pages/admin_panel/listItems.jsx
  src/pages/admin_panel/pending.jsx
  src/pages/login_page/AuthPage.jsx
  src/pages/login_page/ForgetPassword.jsx
  src/pages/login_page/_AuthPage.css
  src/pages/login_page/_ForgetPassword.css
Labels: update

#118 Qa
  .eslintrc.js
  backend/controllers/adminController.js
  backend/controllers/bookController.js
  backend/routes/adminRoutes.js
  backend/routes/bookRoutes.js
  src/App.js
  src/components/footer/Footer.jsx
  src/components/qrcodescanner/QRCodeScanner.jsx
  src/components/timedpopup/TimedPopup.jsx
  src/images/b.jpg
  src/images/background.jpg
  src/images/background1.jpg
  src/images/background2.jpg
  src/images/background3.jpg
  src/images/background4.jpg
  src/images/loginPage-bg.jpeg
  src/images/new1.jpg
  src/images/new2.png
  src/images/new3.png
  src/images/new4.png
  src/images/new5.png
  src/images/potrait lib.jpg
  src/images/quote.png
  src/images/vector1.png
  src/images/vector2.png
  src/images/vector3.png
  src/images/vector4.png
  src/images/vector5.png
  src/images/vector6.png
  src/pages/admin_panel/AdminNav.jsx
  src/pages/admin_panel/_admin-panel-styles.css
  src/pages/admin_panel/admin_pages/AddBook.jsx
  src/pages/admin_panel/admin_pages/AdminAccount.jsx
  src/pages/admin_panel/admin_pages/AllBooks.jsx
  src/pages/admin_panel/admin_pages/_add-book.css
  src/pages/admin_panel/admin_pages/_admin-account.css
  src/pages/admin_panel/listItems.jsx
  src/pages/home_page/ContactUs.jsx
  src/pages/home_page/HomePage.jsx
  src/pages/home_page/_ContactUs.css
  src/pages/home_page/_HomePage.css
  src/pages/home_page/header/Header.jsx
  src/pages/home_page/header/_Header.css
  src/pages/login_page/AuthPage.jsx
  src/pages/login_page/ForgetPass.jsx
  src/pages/login_page/ForgetPassword.jsx
  src/pages/login_page/_AuthPage.css
  src/pages/login_page/_ForgetPassword.css
  src/pages/student_panel/StudentHeader.jsx
  src/pages/student_panel/StudentNav.jsx
  src/pages/student_panel/_StudentHeader.css
  src/pages/student_panel/_StudentNav.css
  src/pages/student_panel/student_pages/_studentAccount.css
  yarn.lock
Labels: update

#124 Manage student
  .eslintrc.js
  backend/controllers/authController.js
  src/pages/admin_panel/AdminPanel.jsx
  src/pages/admin_panel/Deposits.jsx
  src/pages/admin_panel/admin_pages/IssuedBooks.jsx
  src/pages/home_page/HomePage.jsx
  src/pages/home_page/_HomePage.css
  src/pages/login_page/AuthPage.jsx
Labels: update

#132 Manage student
  .eslintrc.js
  backend/controllers/authController.js
  src/pages/admin_panel/AdminPanel.jsx
  src/pages/admin_panel/Deposits.jsx
  src/pages/admin_panel/admin_pages/IssuedBooks.jsx
  src/pages/home_page/HomePage.jsx
  src/pages/home_page/_HomePage.css
  src/pages/login_page/AuthPage.jsx
Labels: update

#138 Firbase ka update
  .firebase/hosting.YnVpbGQ.cache
  firebase.json
  functions/.eslintrc.js
  functions/.gitignore
  functions/controllers/adminController.js
  functions/controllers/authController.js
  functions/controllers/studentController.js
  functions/db.js
  functions/db.test.js
  functions/index.js
  functions/package-lock.json
  functions/package.json
  functions/routes/adminRoutes.js
  functions/routes/authRoutes.js
  functions/routes/studentRoutes.js
  functions/tests/admin.test.js
  functions/tests/setupDatabse.js
  functions/yarn.lock
Labels: update

#139 Firebase ka update
  .firebase/hosting.YnVpbGQ.cache
  firebase.json
  functions/.eslintrc.js
  functions/.gitignore
  functions/controllers/adminController.js
  functions/controllers/authController.js
  functions/controllers/studentController.js
  functions/db.js
  functions/db.test.js
  functions/index.js
  functions/package-lock.json
  functions/package.json
  functions/routes/adminRoutes.js
  functions/routes/authRoutes.js
  functions/routes/studentRoutes.js
  functions/tests/admin.test.js
  functions/tests/setupDatabse.js
  functions/yarn.lock
Labels: update

#141 netlify code updated
  .firebase/hosting.YnVpbGQ.cache
  backend/.gitignore
  backend/controllers/adminController.js
  backend/controllers/authController.js
  backend/controllers/studentController.js
  backend/db.js
  backend/db.test.js
  backend/index.js
  backend/package.json
  backend/routes/adminRoutes.js
  backend/routes/authRoutes.js
  backend/routes/studentRoutes.js
  backend/tests/admin.test.js
  backend/tests/setupDatabse.js
  backend/yarn.lock
  firebase.json
  functions/.eslintrc.js
  functions/package-lock.json
  public/_redirects
  public/index.html
Labels: update, deployment

#140 netlify code updated
  .firebase/hosting.YnVpbGQ.cache
  backend/.gitignore
  backend/controllers/adminController.js
  backend/controllers/authController.js
  backend/controllers/studentController.js
  backend/db.js
  backend/db.test.js
  backend/index.js
  backend/package.json
  backend/routes/adminRoutes.js
  backend/routes/authRoutes.js
  backend/routes/studentRoutes.js
  backend/tests/admin.test.js
  backend/tests/setupDatabse.js
  backend/yarn.lock
  firebase.json
  functions/.eslintrc.js
  functions/package-lock.json
  public/_redirects
  public/index.html
Labels: update, deployment

#145 about_us
  src/App.js
  src/components/footer/Footer.jsx
  src/images/ankit.jpg
  src/images/anshi.jpg
  src/images/jaye.jpg
  src/images/qada.jpg
  src/images/rohit.jpg
  src/pages/about_us/AboutUs.css
  src/pages/about_us/AboutUs.jsx
Labels: enhancement

#146 complete all student pages
  .hintrc
  book-search-app/package.json
  package.json
  src/App.js
  src/pages/admin_panel/admin_pages/AddBook.jsx
  src/pages/student_panel/StudentHeader.jsx
  src/pages/student_panel/StudentNav.jsx
  src/pages/student_panel/StudentOrders.jsx
  src/pages/student_panel/StudentPanel.jsx
  src/pages/student_panel/StudentlistItems.jsx
  src/pages/student_panel/_StudentHeader.css
  src/pages/student_panel/_StudentNav.css
  src/pages/student_panel/_StudentPanel.css
  src/pages/student_panel/student_pages/BooksIssued.jsx
  src/pages/student_panel/student_pages/Feedback.jsx
  src/pages/student_panel/student_pages/History.jsx
  src/pages/student_panel/student_pages/StudentAccount.jsx
  src/pages/student_panel/student_pages/StudentHistory.jsx
  src/pages/student_panel/student_pages/StudentHomepage.jsx
  src/pages/student_panel/student_pages/StudentSearch.jsx
  src/pages/student_panel/student_pages/_feedback.css
  src/pages/student_panel/student_pages/_history.css
  src/pages/student_panel/student_pages/_issuedbook.css
  src/pages/student_panel/student_pages/_studentAccount.css
  src/pages/student_panel/student_pages/_studenthomepage.css
  src/pages/student_panel/student_search/Search.jsx
  src/pages/student_panel/student_search/SearchForm.jsx
  src/pages/student_panel/student_search/SearchResults.jsx
  src/pages/student_panel/student_search/_search.css
  src/pages/student_panel/student_search/_searchform.css
  src/pages/student_panel/student_search/_searchresults.css
  yarn.lock
Labels: enhancement

#147 Scroll-Y top Component added
  src/App.js
  src/components/footer/Footer.jsx
  src/components/footer/_Footer.css
  src/components/scroll/scroll-to-top.jsx
  src/images/qada.jpg
  src/images/qaidj.jpg
  src/pages/about_us/AboutUs.jsx
  src/pages/home_page/header/_Header.css
Labels: bug, enhancement

#150 update spaces
  src/pages/student_panel/StudentPanel.jsx
Labels: enhancement

#151 Qa
  .hintrc
  book-search-app/package.json
  package.json
  src/App.js
  src/components/footer/Footer.jsx
  src/components/footer/_Footer.css
  src/components/scroll/scroll-to-top.jsx
  src/images/ankit.jpg
  src/images/anshi.jpg
  src/images/jaye.jpg
  src/images/qaidj.jpg
  src/images/rohit.jpg
  src/pages/about_us/AboutUs.css
  src/pages/about_us/AboutUs.jsx
  src/pages/admin_panel/admin_pages/AddBook.jsx
  src/pages/home_page/header/_Header.css
  src/pages/student_panel/StudentHeader.jsx
  src/pages/student_panel/StudentNav.jsx
  src/pages/student_panel/StudentOrders.jsx
  src/pages/student_panel/StudentPanel.jsx
  src/pages/student_panel/StudentlistItems.jsx
  src/pages/student_panel/_StudentHeader.css
  src/pages/student_panel/_StudentNav.css
  src/pages/student_panel/_StudentPanel.css
  src/pages/student_panel/student_pages/BooksIssued.jsx
  src/pages/student_panel/student_pages/Feedback.jsx
  src/pages/student_panel/student_pages/History.jsx
  src/pages/student_panel/student_pages/StudentAccount.jsx
  src/pages/student_panel/student_pages/StudentHistory.jsx
  src/pages/student_panel/student_pages/StudentHomepage.jsx
  src/pages/student_panel/student_pages/StudentSearch.jsx
  src/pages/student_panel/student_pages/_feedback.css
  src/pages/student_panel/student_pages/_history.css
  src/pages/student_panel/student_pages/_issuedbook.css
  src/pages/student_panel/student_pages/_studentAccount.css
  src/pages/student_panel/student_pages/_studenthomepage.css
  src/pages/student_panel/student_search/Search.jsx
  src/pages/student_panel/student_search/SearchForm.jsx
  src/pages/student_panel/student_search/SearchResults.jsx
  src/pages/student_panel/student_search/_search.css
  src/pages/student_panel/student_search/_searchform.css
  src/pages/student_panel/student_search/_searchresults.css
  yarn.lock
Labels: documentation, enhancement, backend

#152 term_and_condition_checkbox_added
  .netlify/edge-functions-import-map.json
  backend/.env
  src/pages/admin_panel/_admin-panel-styles.css
  src/pages/admin_panel/listItems.jsx
  src/pages/login_page/AuthPage.jsx
  src/pages/login_page/_AuthPage.css
Labels: enhancement, update

#157 Devlop
  .hintrc
  .netlify/edge-functions-import-map.json
  backend/.env
  book-search-app/package.json
  package.json
  src/App.js
  src/components/footer/Footer.jsx
  src/components/footer/_Footer.css
  src/components/scroll/scroll-to-top.jsx
  src/images/ankit.jpg
  src/images/anshi.jpg
  src/images/jaye.jpg
  src/images/qaidj.jpg
  src/images/rohit.jpg
  src/pages/about_us/AboutUs.css
  src/pages/about_us/AboutUs.jsx
  src/pages/admin_panel/_admin-panel-styles.css
  src/pages/admin_panel/admin_pages/AddBook.jsx
  src/pages/admin_panel/listItems.jsx
  src/pages/home_page/header/_Header.css
  src/pages/login_page/AuthPage.jsx
  src/pages/login_page/_AuthPage.css
  src/pages/student_panel/StudentHeader.jsx
  src/pages/student_panel/StudentNav.jsx
  src/pages/student_panel/StudentOrders.jsx
  src/pages/student_panel/StudentPanel.jsx
  src/pages/student_panel/StudentlistItems.jsx
  src/pages/student_panel/_StudentHeader.css
  src/pages/student_panel/_StudentNav.css
  src/pages/student_panel/_StudentPanel.css
  src/pages/student_panel/student_pages/BooksIssued.jsx
  src/pages/student_panel/student_pages/Feedback.jsx
  src/pages/student_panel/student_pages/History.jsx
  src/pages/student_panel/student_pages/StudentAccount.jsx
  src/pages/student_panel/student_pages/StudentHistory.jsx
  src/pages/student_panel/student_pages/StudentHomepage.jsx
  src/pages/student_panel/student_pages/StudentSearch.jsx
  src/pages/student_panel/student_pages/_feedback.css
  src/pages/student_panel/student_pages/_history.css
  src/pages/student_panel/student_pages/_issuedbook.css
  src/pages/student_panel/student_pages/_studentAccount.css
  src/pages/student_panel/student_pages/_studenthomepage.css
  src/pages/student_panel/student_search/Search.jsx
  src/pages/student_panel/student_search/SearchForm.jsx
  src/pages/student_panel/student_search/SearchResults.jsx
  src/pages/student_panel/student_search/_search.css
  src/pages/student_panel/student_search/_searchform.css
  src/pages/student_panel/student_search/_searchresults.css
  yarn.lock
Labels: update

#156 Update README.md
  README.md
Labels: documentation

#162 Function
  .firebaserc
  .gitignore
  apitests.http
  backend/.gitignore
  backend/controllers/adminController.js
  backend/db.js
  backend/db.test.js
  backend/index.js
  backend/package.json
  backend/routes/adminRoutes.js
  backend/routes/authRoutes.js
  backend/routes/studentRoutes.js
  backend/tests/admin.test.js
  backend/tests/setupDatabse.js
  backend/yarn.lock
  bookflow.sql
  functions/admin-books-get-library.js
  functions/adminBookController.js
  functions/api-test.js
  functions/db-test.js
  functions/db.js
  functions/login.js
  functions/signup.js
  netlify.toml
  package.json
  src/App.js
  src/components/timedpopup/TimedPopup.jsx
  src/pages/login_page/AuthPage.jsx
  yarn.lock
Labels: backend, deployment

#163 Qa
  .gitignore
  .netlify/edge-functions-import-map.json
  apitests.http
  backend/.env
  backend/.gitignore
  backend/controllers/adminController.js
  backend/db.js
  backend/db.test.js
  backend/index.js
  backend/package.json
  backend/routes/adminRoutes.js
  backend/routes/authRoutes.js
  backend/routes/studentRoutes.js
  backend/tests/admin.test.js
  backend/tests/setupDatabse.js
  backend/yarn.lock
  bookflow.sql
  bookflow_data.txt
  functions/admin-books-get-library.js
  functions/adminBookController.js
  functions/api-test.js
  functions/api.js
  functions/db-test.js
  functions/db.js
  functions/hello.js
  functions/login.js
  functions/signup.js
  netlify.toml
  package.json
  src/App.js
  src/components/timedpopup/TimedPopup.jsx
  src/pages/admin_panel/_admin-panel-styles.css
  src/pages/admin_panel/listItems.jsx
  src/pages/login_page/AuthPage.jsx
  src/pages/login_page/_AuthPage.css
  yarn.lock
Labels: update

#164 Update README.md
  README.md
Labels: documentation, update

#166 terms and condition page completed
  .gitignore
  src/App.js
  src/pages/admin_panel/admin_pages/AddBook.jsx
  src/pages/login_page/term_condition/TermsAndConditions.css
  src/pages/login_page/term_condition/TermsAndConditions.jsx
Labels: documentation

#175 Qa
  book-search-app/package.json
Labels: update

#174 admin dashboard backend complete
  apitests.http
  backend/.env
  functions/admin-books-get-bookbank.js
  functions/admin-dashboard.js
  functions/admin-get-students.js
  functions/admin-history-get-bookbank.js
  functions/admin-history-get-library.js
  functions/admin-issued-get-bookbank.js
  functions/admin-issued-get-library.js
  functions/admin-pending-get-bookbank.js
  functions/admin-pending-get-library.js
  functions/student-history-get-books.js
  rohit-api-tests.http
  src_directory_tree.json
Labels: enhancement, backend, deployment

#191 Qa
  .gitignore
  apitests.http
  backend/.env
  backend/controllers/authController.js
  backend/controllers/studentController.js
  book-search-app/package.json
  functions/admin-books-get-bb.js
  functions/admin-books-get-lib.js
  functions/admin-books-get-test.js
  functions/admin-books-post-bb.js
  functions/admin-books-post-lib.js
  functions/admin-books-post-test.js
  functions/admin-dashboard.js
  functions/admin-get-students.js
  functions/admin-history-get-bb.js
  functions/admin-history-get-lib.js
  functions/admin-issued-get-bb.js
  functions/admin-issued-get-lib.js
  functions/admin-pending-get-bb.js
  functions/admin-pending-get-lib.js
  functions/api-test.js
  functions/email-verify.js
  functions/forget-password.js
  functions/login.js
  functions/signup.js
  functions/student-history-get-lib.js
  package.json
  rohit-api-tests.http
  src/App.js
  src/components/footer/Footer.jsx
  src/components/footer/_Footer.css
  src/pages/admin_panel/AdminPanel.jsx
  src/pages/admin_panel/adminDashboard.jsx
  src/pages/admin_panel/admin_pages/AddBook.jsx
  src/pages/admin_panel/admin_pages/AdminHistory.jsx
  src/pages/admin_panel/admin_pages/AllBooks.jsx
  src/pages/admin_panel/admin_pages/IssuedBooks.jsx
  src/pages/admin_panel/admin_pages/PendingIssue.jsx
  src/pages/admin_panel/admin_pages/_add-book.css
  src/pages/admin_panel/admin_pages/_admin-history.css
  src/pages/admin_panel/admin_pages/_all-books.css
  src/pages/admin_panel/admin_pages/_issued-book.css
  src/pages/admin_panel/admin_pages/_manage-students.css
  src/pages/admin_panel/admin_pages/_pending-issue.css
  src/pages/email_verified/EmailVerified.jsx
  src/pages/email_verified/_EmailVerifiedPage.css
  src/pages/login_page/AuthPage.jsx
  src/pages/login_page/ForgetPassword.jsx
  src/pages/login_page/_ForgetPassword.css
  src/pages/student_panel/StudentPanel.jsx
  src/pages/student_panel/StudentlistItems.jsx
  src/pages/student_panel/student_pages/Feedback.jsx
  src/pages/student_panel/student_pages/StudentAccount.jsx
  src/pages/student_panel/student_pages/StudentHistory.jsx
  src/pages/student_panel/student_pages/StudentSearch.jsx
  src/pages/student_panel/studentdashboard.jsx
  src/pages/term_condition/TermsAndConditions.css
  src/pages/term_condition/TermsAndConditions.jsx
  src_directory_tree.json
  yarn.lock
Labels: enhancement, backend, deployment

#195 Devlop
  .gitignore
  apitests.http
  backend/.env
  backend/controllers/authController.js
  backend/controllers/studentController.js
  book-search-app/package.json
  functions/admin-books-get-bb.js
  functions/admin-books-get-lib.js
  functions/admin-books-get-test.js
  functions/admin-books-post-bb.js
  functions/admin-books-post-lib.js
  functions/admin-books-post-test.js
  functions/admin-dashboard.js
  functions/admin-get-students.js
  functions/admin-history-get-bb.js
  functions/admin-history-get-lib.js
  functions/admin-issued-get-bb.js
  functions/admin-issued-get-lib.js
  functions/admin-pending-get-bb.js
  functions/admin-pending-get-lib.js
  functions/email-verify.js
  functions/forget-password.js
  functions/login.js
  functions/signup.js
  functions/student-history-get-lib.js
  package.json
  rohit-api-tests.http
  src/App.js
  src/components/footer/Footer.jsx
  src/components/footer/_Footer.css
  src/pages/admin_panel/AdminPanel.jsx
  src/pages/admin_panel/adminDashboard.jsx
  src/pages/admin_panel/admin_pages/AddBook.jsx
  src/pages/admin_panel/admin_pages/AdminHistory.jsx
  src/pages/admin_panel/admin_pages/AllBooks.jsx
  src/pages/admin_panel/admin_pages/IssuedBooks.jsx
  src/pages/admin_panel/admin_pages/PendingIssue.jsx
  src/pages/email_verified/EmailVerified.jsx
  src/pages/email_verified/_EmailVerifiedPage.css
  src/pages/login_page/AuthPage.jsx
  src/pages/login_page/ForgetPassword.jsx
  src/pages/login_page/_ForgetPassword.css
  src/pages/student_panel/StudentPanel.jsx
  src/pages/student_panel/StudentlistItems.jsx
  src/pages/student_panel/student_pages/StudentAccount.jsx
  src/pages/student_panel/student_pages/StudentHistory.jsx
  src/pages/student_panel/student_pages/StudentSearch.jsx
  src/pages/student_panel/studentdashboard.jsx
  src/pages/term_condition/TermsAndConditions.css
  src/pages/term_condition/TermsAndConditions.jsx
  src_directory_tree.json
  yarn.lock
Labels: update

#197 Qa
  .gitignore
  apitests.http
  backend/.env
  backend/controllers/authController.js
  backend/controllers/studentController.js
  book-search-app/package.json
  functions/admin-books-get-bb.js
  functions/admin-books-get-lib.js
  functions/admin-books-get-test.js
  functions/admin-books-post-bb.js
  functions/admin-books-post-lib.js
  functions/admin-books-post-test.js
  functions/admin-dashboard.js
  functions/admin-get-students.js
  functions/admin-history-get-bb.js
  functions/admin-history-get-lib.js
  functions/admin-issued-get-bb.js
  functions/admin-issued-get-lib.js
  functions/admin-pending-get-bb.js
  functions/admin-pending-get-lib.js
  functions/email-verify.js
  functions/forget-password.js
  functions/login.js
  functions/signup.js
  functions/student-history-get-lib.js
  package.json
  rohit-api-tests.http
  src/App.js
  src/components/footer/Footer.jsx
  src/components/footer/_Footer.css
  src/pages/admin_panel/AdminPanel.jsx
  src/pages/admin_panel/adminDashboard.jsx
  src/pages/admin_panel/admin_pages/AddBook.jsx
  src/pages/admin_panel/admin_pages/AdminHistory.jsx
  src/pages/admin_panel/admin_pages/AllBooks.jsx
  src/pages/admin_panel/admin_pages/IssuedBooks.jsx
  src/pages/admin_panel/admin_pages/PendingIssue.jsx
  src/pages/email_verified/EmailVerified.jsx
  src/pages/email_verified/_EmailVerifiedPage.css
  src/pages/login_page/AuthPage.jsx
  src/pages/login_page/ForgetPassword.jsx
  src/pages/login_page/_ForgetPassword.css
  src/pages/student_panel/StudentPanel.jsx
  src/pages/student_panel/StudentlistItems.jsx
  src/pages/student_panel/student_pages/StudentAccount.jsx
  src/pages/student_panel/student_pages/StudentHistory.jsx
  src/pages/student_panel/student_pages/StudentSearch.jsx
  src/pages/student_panel/studentdashboard.jsx
  src/pages/term_condition/TermsAndConditions.css
  src/pages/term_condition/TermsAndConditions.jsx
  src_directory_tree.json
  yarn.lock
Labels: enhancement, backend, deployment

#198 Book_Issue_Completed
  src/pages/student_panel/student_pages/StudentSearch.jsx
Labels: enhancement, update

#199 Devlop
  LICENSE
  apitests.http
  functions/admin-books-get-bookbank.js
  functions/admin-books-post-bb.js
  functions/admin-books-post-lib.js
  functions/admin-books-post-test.js
  functions/admin-history-get-bookbank.js
  functions/admin-history-get-library.js
  functions/admin-issued-get-bookbank.js
  functions/admin-issued-get-library.js
  functions/admin-pending-get-bookbank.js
  functions/admin-pending-get-library.js
  functions/api-test.js
  functions/email-verify.js
  functions/forget-password.js
  functions/login.js
  functions/signup.js
  functions/student-books-get-search.js
  functions/student-history-get-books.js
  functions/student-issued-get-bookbank.js
  functions/student-issued-get-library.js
  functions/student-returned-get-books.js
  package.json
  src/App.js
  src/components/footer/Footer.jsx
  src/components/footer/_Footer.css
  src/pages/admin_panel/admin_pages/_add-book.css
  src/pages/admin_panel/admin_pages/_admin-history.css
  src/pages/admin_panel/admin_pages/_all-books.css
  src/pages/admin_panel/admin_pages/_issued-book.css
  src/pages/admin_panel/admin_pages/_manage-students.css
  src/pages/admin_panel/admin_pages/_pending-issue.css
  src/pages/contact-us/ContactUs.css
  src/pages/contact-us/ContactUs.jsx
  src/pages/email_verified/EmailVerified.jsx
  src/pages/email_verified/_EmailVerifiedPage.css
  src/pages/login_page/AuthPage.jsx
  src/pages/login_page/ForgetPassword.jsx
  src/pages/login_page/term_condition/TermsAndConditions.css
  src/pages/login_page/term_condition/TermsAndConditions.jsx
  src/pages/student_panel/StudentOrders.jsx
  src/pages/student_panel/StudentlistItems.jsx
  src/pages/student_panel/student_pages/Feedback.jsx
  src/pages/student_panel/student_pages/StudentHistory.jsx
  src/pages/student_panel/student_pages/StudentSearch.jsx
  yarn.lock
Labels: update, backend

#201 Qa
  package.json
  src/pages/student_panel/student_pages/StudentSearch.jsx
Labels: update, backend

#200 Qa
  package.json
  src/App.js
  src/pages/student_panel/student_pages/StudentSearch.jsx
Labels: update, backend, deployment

#204 New README.md
  README.md
Labels: documentation
