Repository rohitagr0310/Bookflow-app, pull requests merged in 2023-08, with the labels that each got.

#28 issue solve
  src/pages/student_panel/student_pages/Feedback.jsx
  src/pages/student_panel/student_pages/_feedback.css
Labels: bug

#30 Update README.md
  README.md
Labels: documentation

#32 inserted card components in student homepage
  src/pages/student_panel/StudentPanel.jsx
Labels: documentation, enhancement

#43 adminpanel - all books
  src/images/loginPage-bg1.jpg
  src/pages/admin_panel/admin_pages/AddBook.jsx
  src/pages/admin_panel/admin_pages/AllBooks.jsx
  src/pages/login_page/AuthPage.jsx
  src/pages/login_page/_AuthPage.css
Labels: enhancement, update

#42 Login page updated
  src/images/loginPage-bg1.jpg
  src/pages/login_page/AuthPage.jsx
  src/pages/login_page/_AuthPage.css
Labels: enhancement

#45 I am created search page with small sample of css
  src/App.js
  src/images/loginPage-bg.jpeg
  src/pages/student_panel/StudentNav.jsx
  src/pages/student_panel/_StudentNav.css
  src/pages/student_panel/student_pages/Feedback.jsx
  src/pages/student_panel/student_pages/Search.jsx
  src/pages/student_panel/student_search/Search.jsx
  src/pages/student_panel/student_search/SearchForm.jsx
  src/pages/student_panel/student_search/SearchResults.jsx
  src/pages/student_panel/student_search/_search.css
  src/pages/student_panel/student_search/_searchform.css
  src/pages/student_panel/student_search/_searchresults.css
Labels: bug, enhancement, update

#47 Home_page_update
  src/images/b.jpg
  src/images/background1.jpg
  src/images/background2.jpg
  src/images/background3.jpg
  src/images/background4.jpg
  src/images/loginPage-bg.jpeg
  src/pages/home_page/HomePage.jsx
  src/pages/home_page/_HomePage.css
Labels: enhancement

#50 All commits from the last week
  src/App.js
  src/images/b.jpg
  src/images/background1.jpg
  src/images/background2.jpg
  src/images/background3.jpg
  src/images/background4.jpg
  src/images/loginPage-bg1.jpg
  src/pages/admin_panel/admin_pages/AddBook.jsx
  src/pages/admin_panel/admin_pages/AllBooks.jsx
  src/pages/home_page/HomePage.jsx
  src/pages/home_page/_HomePage.css
  src/pages/login_page/AuthPage.jsx
  src/pages/login_page/_AuthPage.css
  src/pages/student_panel/StudentNav.jsx
  src/pages/student_panel/_StudentNav.css
  src/pages/student_panel/student_pages/Feedback.jsx
  src/pages/student_panel/student_pages/Search.jsx
  src/pages/student_panel/student_search/Search.jsx
  src/pages/student_panel/student_search/SearchForm.jsx
  src/pages/student_panel/student_search/SearchResults.jsx
  src/pages/student_panel/student_search/_search.css
  src/pages/student_panel/student_search/_searchform.css
  src/pages/student_panel/student_search/_searchresults.css
Labels: documentation, update

#52 Devlop
  backend/db.js
  backend/package.json
  backend/yarn.lock
  bookflow.sql
  src/App.js
  src/components/footer/Footer.jsx
  src/components/footer/extra_pages/About.jsx
  src/components/footer/extra_pages/_aboutus.css
  tempCodeRunnerFile.javascript
Labels: enhancement, help wanted, update, backend

#55 26-08-2023_update
  src/App.js
  src/components/footer/Footer.jsx
  src/components/footer/extra_pages/About.jsx
  src/components/footer/extra_pages/_aboutus.css
  src/images/background1.jpg
  src/images/background2.jpg
  src/images/background3.jpg
  src/images/background4.jpg
  src/pages/home_page/_HomePage.css
  tempCodeRunnerFile.javascript
Labels: help wanted, update

#61 devlop branch updated for new pushes that was done in qa
  .eslintrc.js
  backend/controllers/adminController.js
  backend/controllers/authController.js
  backend/db.js
  backend/index.js
  backend/package.json
  backend/routes/adminRoutes.js
  backend/routes/authRoutes.js
  backend/yarn.lock
  src/pages/login_page/AuthPage.jsx
  src/pages/login_page/_AuthPage.css
Labels: documentation, duplicate, update

#60 footer_update
  src/components/footer/Footer.jsx
  src/components/footer/_Footer.css
Labels: update

#63 testimonials
  src/App.js
  src/components/footer/_Footer.css
  src/pages/home_page/HomePage.jsx
  src/pages/home_page/_HomePage.css
  src/pages/student_panel/StudentHeader.jsx
  src/pages/student_panel/StudentNav.jsx
  src/pages/student_panel/StudentPanel.jsx
  src/pages/student_panel/_StudentHeader.css
  src/pages/student_panel/student_pages/BookIssued.jsx
  src/pages/student_panel/student_pages/BooksIssued.jsx
  src/pages/student_panel/student_pages/Feedback.jsx
  src/pages/student_panel/student_pages/StudentHomepage.jsx
  src/pages/student_panel/student_pages/_feedback.css
  src/pages/student_panel/student_pages/_issuedbook.css
  src/pages/student_panel/student_pages/_studentAccount.css
  src/pages/student_panel/student_pages/_studenthomepage.css
Labels: enhancement

#94 navigation for login page
  package.json
  src/pages/login_page/AuthPage.jsx
  tempCodeRunnerFile.javascript
Labels: documentation, duplicate, enhancement

#96 popup component
  backend/controllers/adminController.js
Labels: duplicate, enhancement, good first issue, backend

#97 popup component
  src/components/timedpopup/TimedPopup.jsx
  src/pages/login_page/AuthPage.jsx
Labels: documentation, duplicate, enhancement, backend

#99 qr code scanner fixed and updated
  src/components/qrcodescanner/QRCodeScanner.jsx
  src/pages/admin_panel/AdminHeader.jsx
  src/pages/admin_panel/AdminNav.jsx
  src/pages/admin_panel/AdminPanel.jsx
  src/pages/admin_panel/_admin-nav.css
  src/pages/login_page/_AuthPage.css
  src/pages/student_panel/_StudentNav.css
Labels: bug, enhancement, good first issue, backend
